spring:
  application:
    name: api
  config:
    import:
      optional:./secrets.properties
      # Contains property 'jwt.secrets' environment variable
  datasource:
    url: jdbc:sqlite:db/gift.db
    driver-class-name: org.sqlite.JDBC
  flyway:
    enabled: true
    locations: db/migration
    validate-on-migrate: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: 5000
  servlet:
    context-path: /api